name: ZornoKoruma
version: 1.1
main: com.zornoely.koruma.Main
api-version: 1.20
commands:
  balta:
    description: Koruma baltasi verir.
  kazma:
    description: Tekil blok secim kazmasi verir.
  koruma:
    description: Koruma komutlari.
    
